- name: Set DNS servers
  ansible.builtin.shell:
    cmd: |
      sed -i '/nameserver .*/d' /etc/resolv.conf
      echo 'nameserver 192.168.1.136' >> /etc/resolv.conf
      echo 'nameserver 9.9.9.9' >> /etc/resolv.conf